### ISSUE TITLE
Link to the project

### ISSUE THREAD

**Issue by Kingjosh007** [Kingjosh007/space-travelers-hub#25]
We are two (2) working on this project. Here is the [link to the Kanban board](https://github.com/Kingjosh007/space-travelers-hub/projects/1) where you can see how the tasks were assigned.

**Comment by elyor-doniyorov** [comment]
Hi @Kingjosh007 and @mwanawabangona, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
![Screenshot (74)_LI](https://user-images.githubusercontent.com/67087664/146795400-ee9b72ef-f7c2-4592-8c48-4ba56ef52cc3.jpg)
- [ ] According to the requirements if a team has 2 members your tasks should be 17.  You have an overall 18 tasks but 1 is extra which came from `Team 3` tasks. Kindly remove it!

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kingjosh007** [comment]
Hi @elyor-doniyorov 
That card has been removed. Thanks for pointing it out.

**Comment by bimbolabuari** [comment]
# Project Approved 🚀

Hi Team🥇,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉



Cheers and Happy coding!👏👏👏



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
